# Étape 1 : Builder React
FROM node:24.1.0-slim AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build  

# Étape 2 : Serveur Nginx
FROM nginx:1.28.0-alpine-slim
COPY --from=build /app/build /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
