services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: mybank_frontend
    ports:
      - "3001:80"  
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: mybank_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www
    working_dir: /var/www
    command: symfony server:start --no-tls --allow-http --port=8000 --allow-all-ip
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/mybank?serverVersion=8.0
    depends_on:
      - db

  db:
    image: mysql:8.3
    container_name: mybank_db
    restart: always
    environment:
      MYSQL_DATABASE: mybank
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mybank_phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"

  nginx:
    image: nginx:1.28.0-alpine-slim
    container_name: mybank_nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.config:/etc/nginx/conf.d/default.config:ro
    depends_on:
      - frontend
      - backend

volumes:
  db_data:
