services:
  # Base de données
  db:
    image: mysql:8.3
    container_name: mybank_db
    restart: always
    environment:
      MYSQL_DATABASE: mybank
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # Backend Symfony
  backend:
    image: ghcr.io/christh2022/mybank/backend:latest
    container_name: mybank_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mysql://root:root@db:3306/mybank?serverVersion=8.0
    depends_on:
      - db

  # Frontend React
  frontend:
    image: ghcr.io/christh2022/mybank/frontend:latest
    container_name: mybank_frontend
    restart: always
    depends_on:
      - backend

  # PhpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mybank_phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"

  # Nginx (reverse proxy)
  nginx:
    image: nginx:1.28.0-alpine-slim
    container_name: mybank_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  db_data:
