lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600 # 1 hour
    token_extractors:
        cookie:
            name: BEARER           # le nom du cookie où le JWT est stocké
        authorization_header:
            prefix: Bearer         # toujours possible depuis Authorization header
