security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/auth/login
            stateless: true
            json_login:
                check_path: /auth/login  
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            login_throttling:   
                max_attempts: 5
                interval: '15 minutes'

        register:
            pattern: ^/auth/register
            stateless: true
            security: false

        check:
            pattern: ^/auth/check
            stateless: true
            jwt: ~

        refresh:
            pattern: ^/auth/refresh
            stateless: true
            jwt: ~

        api:
            pattern: ^/api
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/auth/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/auth/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/admin, roles: ROLE_ADMIN }   # Routes admin
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }   # Toutes les autres routes API
        - { path: ^/auth/check, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/auth/refresh, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
