name: Install dependencies

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install-dependencies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          submodules: true  # <-- important pour Option B

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3.8'
          extensions: pdo, pdo_mysql, mbstring, xml, curl

      - name: Install backend dependencies
        working-directory: ./backend
        run: composer install --no-interaction --prefer-dist
